# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xS5gaNQZORuhMxXjc7ztu8RFq-Kkdr-l
"""


import streamlit as st
import tensorflow as tf
from tensorflow import keras
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
from skimage import transform
import cv2

def load(filename):
   np_image = Image.open(filename)
   plt.imshow(np_image, cmap = 'gray')
   plt.xticks([])
   plt.yticks([])
   np_image = np.array(np_image).astype('float32')/255
   np_image = transform.resize(np_image, (256, 256, 3))
   np_image = np.expand_dims(np_image, axis=0)
   return np_image

st.title('IARA - TBC Detector')
st.subheader('Your health, our mission')
img = st.file_uploader("Choose a file")
if img:
    model = tf.keras.models.load_model(r"C:\Users\julik\OneDrive\Desktop\IARAsStreamlitApp\TBC_CNN_Fusion_AugementedData.h5")
    img = load(img)
    st.image(img)
    st.subheader("TBC percentage: %" + ((str((model.predict(img))*100)).split("[")[2]).split("]")[0])
    st.write("It is important to know this ISN'T A DIAGNOSIS and this should be checked by an expert and blah blah blah")
